### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by DoHe** [Byhiras/pyavroc#11]
Currently the setup.py build process fails at the extension building step. 
The error message is:
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
With only warnings before this.
Is python3 support planned?

**Comment by walshb** [comment]
It's not only planned, it's implemented! I just never got round to fixing the last few bugs.

I've made it available in my own repo for now. Can you try this:

```
git clone -b bw-py3 https://github.com/walshb/pyavroc.git
cd pyavroc/
PYTHON=python3 ./clone_avro_and_build.sh 
```

**Comment by DoHe** [comment]
Thanks, that is great. The building works just fine and all tests pass.
I'll let this issue open until I have time to actually test it in some actual code to see if it works everywhere.

**Comment by DoHe** [comment]
Sorry that it took me so long. I just tried it out more thoroughly and it works fine. Thank you!
