### ISSUE TITLE
No difference between types True and types False

### ISSUE THREAD

**Issue by MariusDieck** [Byhiras/pyavroc#12]
Hey,

i ran some performance tests with pyavroc, however i could not find any performance difference when using types True and False. This is my (simplified) Code:

avroFile = open(self.avrofile)
reader = pymzavro.reader.PymzAvroReader(avroFile, readerType=True)
for spectrum in reader:
    spectrum.user

Am i doing something wrong?

Greetings

Marius

**Comment by walshb** [comment]
You're not doing anything wrong, you're doing everything right.

Those numbers are from Python 2.6. The results for Python 2.7 are pretty much equal for dictionaries and objects.

I've put some benchmarking in a branch; click the links here to see the different timings: https://travis-ci.org/walshb/pyavroc

I will update the doc sometime soonish.

Cheers

Ben
