### ISSUE TITLE
problem when reusing a record type in a union

### ISSUE THREAD

**Issue by ilveroluca** [Byhiras/pyavroc#14]
I've found a problem when trying to serialize records whose schema reuses a record type within a union.  The test in this commit demonstrates the problem: ilveroluca/pyavroc@2a08f1f425784023ce48019b2227c3e4a53e39a8

The call to `serialize` raises an exception `IOError: Write error: when writing to foo.c2`

**Comment by walshb** [comment]
I think this fixes it:

https://github.com/walshb/pyavroc/commit/d4a9df0033e6a64eaef846c49ba33570092b030d

**Comment by ilveroluca** [comment]
Fix merged in d4a9df0033e6a64eaef846c49ba33570092b030d.  Closing issue.
