### ISSUE TITLE
Record comparison crashes on NULL values

### ISSUE THREAD

**Issue by ubarkai** [Byhiras/pyavroc#15]
>>> import json, pyavroc
    >>> t = pyavroc.create_types(json.dumps({'name': 'A', 'type': 'record', 'fields': [{'name': 'x', 'type': 'string'}]}))
    >>> t.A() == t.A()
    [1]    69011 segmentation fault  ~/env/bin/python

**Comment by walshb** [comment]
I have pushed a fix to master. Please can you try it now? Thanks.

**Comment by ubarkai** [comment]
Yes, it works. Thanks.
