### ISSUE TITLE
Static Build Fails

### ISSUE THREAD

**Issue by Tho77** [Byhiras/pyavroc#25]
I've spent a decent amount of time on this, but I'm out of my element on the c compiling.

I'm trying to run the clone_avro_and_build.sh --static so that it will include the libraries so that I can deploy the full package to an AWS Lambda.

However after the build, the tests fail with:
`ImportError: libavro.so.22.0.0: cannot open shared object file: No such file or directory`

During the build script, it outputs the line:
`export PYAVROC_LIBS=pthread`
Something tells me pthread is not the correct value there, but I can't seem to figure out what it should be.

**Comment by walshb** [comment]
If you run clone_avro_and_build.sh without --static, then running again with --static won't work.

Try this:

```
rm local_avro/dist/lib/libavro.so*
./clone_avro_and_build.sh --static
```

Re: PYAVROC_LIBS, these should be automatically detected during the avro build, then used by clone_avro_and_build.sh. You might want to install, for example, zlib (`apt-get install zlib1g-dev` on Ubuntu), then rebuild:

```
rm -r local_avro/build local_avro/dist
./clone_avro_and_build.sh --static
```

See the Travis build for an example of PYAVROC_LIBS: https://travis-ci.org/Byhiras/pyavroc/jobs/154415457

**Comment by Tho77** [comment]
Thanks for the help, it was indeed due to the fact that I had already compiled it without --static.
